# Generated by Django 3.0.6 on 2020-07-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='six',
            name='imagereason',
            field=models.TextField(default='안녕하세요?', max_length=300),
        ),
    ]
