# Generated by Django 3.0.6 on 2020-07-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('six', '0003_auto_20200706_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='six',
            old_name='imagereason',
            new_name='imageinfo2',
        ),
    ]
